AWSTemplateFormatVersion: 2010-09-09

Description: >-
  AWS CloudFormation ASG Template

# HealthCheck sur /wp-login.php

Parameters:

  StackName:
    Description: "Stack Name"
    Type: "String"

  VpcId:
    Description: "VPC ID"
    Type: "String"

  AmiIdentifier:
    Type: String
    Description: The AMI identifier to deploy.
    Default: "ami-030f26d9e722e2b3c"

  InstanceType:
    Type: String
    Description: The Instance type.
    Default: "t2.micro"

  PublicSubnetAId:
    Description: The subnet ID of PublicSubnetA
    Type: "String"
  
  PublicSubnetBId:
    Description: The subnet ID of PublicSubnetB
    Type: "String"

  PublicSubnetCId:
    Description: The subnet ID of PublicSubnetC
    Type: "String"

  SecurityGroupWebServerSSHId:
    Description: "The security group ID to use for SSH"
    Type: "String"

  SecurityGroupWebServerHTTPId:
    Description: "The security group ID to use for HTTP"
    Type: "String"

  EC2SNSTopic:
    Description: "EC2 SNS Topic ARN"
    Type: "String"

  IAMSecretsARN:
    Description: "IAM Secrets ARN"
    Type: "String"  

  Toggle:
    Description: "Allow trigger ASG Update"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

  GithubRepo:
    Type: String
    Description: Github Repo.
    Default: "docker-nginx-wordpress-mysql"

  PublicIP:
    Description: "My Own Public IP"
    Type: "String"
    Default: '0.0.0.0/0'

  DBInstanceEndpoint:
    Description: "DBInstance Endpoint"
    Type: "String"
  
  DBInstanceReplicaEndpoint:
    Description: "DBInstance Replica Endpoint"
    Type: "String"  

Resources:

  WebSiteInstanceRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  
  WebSiteRolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "root"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action:
            - 'secretsmanager:GetSecretValue'
            - 'secretsmanager:GetSecretValue'
            - 'secretsmanager:DescribeSecret'
            - 'secretsmanager:ListSecretVersionIds'
            Resource:
              - Ref: IAMSecretsARN
      Roles: 
        - 
          Ref: "WebSiteInstanceRole"

  WebSiteInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref WebSiteInstanceRole

  WebsiteLaunchConfig:
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '1'
        MaxBatchSize: '1'
        PauseTime: PT12M5S
        WaitOnResourceSignals: true
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      ImageId:
        Ref: AmiIdentifier
      InstanceType:
        Ref: InstanceType
      KeyName:
          Fn::Sub: "${StackName}_keypair"
      SecurityGroups:
        - Ref: SecurityGroupWebServerSSHId
        - Ref: SecurityGroupWebServerHTTPId
      IamInstanceProfile:
        Ref: WebSiteInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export DOCKER_DIR="docker-nginx-wordpress-mysql"
          cd /home/admin/
          sudo git clone https://github.com/hgalvani/docker-nginx-wordpress-mysql.git
          echo "PROJECT_NAME=anteverse" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "MYSQL_HOST=${DBInstanceEndpoint}" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "MYSQL_PORT=3306" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "MYSQL_DBNAME=anteverse" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "MYSQL_USER=anteverse" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "MYSQL_PASSWORD=anteverse" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "NGINX_PORT=80" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "NGINX_ALLOWED_IP_FOR_ADMIN=${PublicIP}" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "AWS_ACCESS_KEY_ID=$(aws secretsmanager get-secret-value --secret-id anteverse-iam-secret | jq --raw-output .SecretString | jq -r ."aws_access_key_id")" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          echo "AWS_SECRET_ACCESS_KEY=$(aws secretsmanager get-secret-value --secret-id anteverse-iam-secret | jq --raw-output .SecretString | jq -r ."aws_secret_access_key")" | sudo tee -a /home/admin/docker-nginx-wordpress-mysql/prod/.env
          cd /home/admin/docker-nginx-wordpress-mysql/prod/
          /usr/local/bin/docker-compose up -d

          
          

  WebsiteScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName:
        Ref: WebsiteLaunchConfig
      HealthCheckGracePeriod: 300
      VPCZoneIdentifier:
        - Ref: PublicSubnetAId
        - Ref: PublicSubnetBId
        - Ref: PublicSubnetCId
      DesiredCapacity: 1
      MaxSize: 1
      MinSize: 1
      TargetGroupARNs:
        - Ref: WebsiteTargetGroup
      NotificationConfigurations:
      - TopicARN:
          Ref: EC2SNSTopic
        NotificationTypes: 
          - autoscaling:EC2_INSTANCE_LAUNCH
          - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
          - autoscaling:EC2_INSTANCE_TERMINATE
          - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
          - autoscaling:TEST_NOTIFICATION
      Tags:
          -
            Key: Name
            Value:
              Fn::Sub: "${StackName}-frontweb"
            PropagateAtLaunch: true     
      
  ScaleUpPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: WebsiteScalingGroup
      Cooldown: '60'
      ScalingAdjustment: '1'

  CPUAlarmHigh:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: ScaleUpPolicy
      AlarmDescription: Scale-up if CPU > 80% for 5 minutes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: WebsiteScalingGroup
      EvaluationPeriods: '1'
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: '300'
      Statistic: Average
      Threshold: '80'
    
  CPUAlarmLow:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - Ref: ScaleDownPolicy
      AlarmDescription: Scale-down if CPU < 70% for 5 minutes
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: WebsiteScalingGroup
      EvaluationPeriods: '1'
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: '300'
      Statistic: Average
      Threshold: '70'

  ScaleDownPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: WebsiteScalingGroup
      Cooldown: '60'
      ScalingAdjustment: '-1'
  
  WebsiteTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId:
        Ref: VpcId
  
  WebsiteLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - Ref: SecurityGroupWebServerHTTPId
      Subnets:
        - Ref: PublicSubnetAId
        - Ref: PublicSubnetBId
        - Ref: PublicSubnetCId
  
 
  WebsiteLoadBlancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      LoadBalancerArn:
        Ref: WebsiteLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: WebsiteTargetGroup


# Outputs:
#   AutoScalingGroup:
#     Description: AutoScaling Group Name
#     Export:
#       Name: !Sub '${AWS::StackName}-AutoScalingGroup'
#     Value: !Ref AutoScalingGroup
#   StackName:
#     Description: Stack Name
#     Value: !Ref 'AWS::StackName'
#   URL:
#     Description: The URL of the website
#     Value: !Join 
#       - ''
#       - - 'http://'
#         - !GetAtt 
#           - ElasticLoadBalancer
#           - DNSName