AWSTemplateFormatVersion: "2010-09-09"

Description: >
    AWS CloudFormation EFS Template

Parameters:

  StackName:
    Description: "Stack Name"
    Type: "String"

  VpcId:
    Description: "VPC ID"
    Type: "String"

  PrivateSubnetAId:
    Description: The subnet ID of PrivateSubnetA
    Type: "String"

  PrivateSubnetBId:
    Description: The subnet ID of PrivateSubnetB
    Type: "String"

  PrivateSubnetCId:
    Description: The subnet ID of PrivateSubnetC
    Type: "String"

  SecurityGroupEFSNFSAzAId:
    Description: "The security group ID to use for EFS for AzA"
    Type: "String"

  SecurityGroupEFSNFSAzBId:
    Description: "The security group ID to use for EFS for AzB"
    Type: "String"

  SecurityGroupEFSNFSAzCId:
    Description: "The security group ID to use for EFS for AzC"
    Type: "String"   

Resources:
  
  FileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: Name
          Value:
            Fn::Sub: "${StackName}-SharedFileSystem"

  MountTargetResourceAzA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: FileSystemResource
      SubnetId:
        Ref: PrivateSubnetAId
      SecurityGroups:
      - Ref: SecurityGroupEFSNFSAzAId

  MountTargetResourceAzB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: FileSystemResource
      SubnetId:
        Ref: PrivateSubnetBId
      SecurityGroups:
      - Ref: SecurityGroupEFSNFSAzBId

  MountTargetResourceAzC:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: FileSystemResource
      SubnetId:
        Ref: PrivateSubnetCId
      SecurityGroups:
      - Ref: SecurityGroupEFSNFSAzCId
 
  # AccessPointResource:
  #   Type: 'AWS::EFS::AccessPoint'
  #   Properties:
  #     FileSystemId:
  #       Ref: FileSystemResource
  #     # PosixUser:
  #     #   Uid: "33"
  #     #   Gid: "33"
  #     #   SecondaryGids:
  #     #     - "101"
  #     #     - "102"
  #     RootDirectory:
  #       # CreationInfo:
  #       #   OwnerGid: "708798"
  #       #   OwnerUid: "7987987"
  #       #   Permissions: "0755"
  #       Path:
  #         Fn::Sub: "/app/${StackName}"
  #     AccessPointTags:
  #         -
  #           Key: Name
  #           Value:
  #             Fn::Sub: "${StackName}-efs-accesspoint"    

Outputs:

  FileSystemResourceId:
    Value:
      Ref: FileSystemResource
    Export:
      Name: FileSystemResourceId

  # AccessPointResourceId:
  #   Value:
  #     Ref: AccessPointResource
  #   Export:
  #     Name: AccessPointResourceId

  # AccessPointResourceARN:
  #   Value:
  #     Fn::GetAtt:
  #     - AccessPointResource
  #     - Arn
  #   Export:
  #     Name: AccessPointResourceARN
            
